var obj = { x: 1, y: 2, z: 3 };
console.log(obj.x);
var x = obj.x, y = obj.y, z = obj.z;
console.log(x);
var array = [1, 2, 3];
console.log(array[0]);
var x = array[0], y = array[1], z = array[2];
console.log(x);
var arrai = [1, 2, 3, 4];
var x = arrai[0], y = arrai[1], rest = arrai.slice(2);
console.log(x, y, rest);
